# POST http://localhost:3000/game/cmu45txyw000022qjlgt4d6ny/join HTTP/1.1
# content-type: application/json

# {
#     "imie": "karolina"
# }

# GET http://localhost:3000/games/cmu45txyw000022qjlgt4d6ny HTTP/1.1


# POST http://localhost:3000/games/cmu45txyw000022qjlgt4d6ny/roll
# content-Type: application/json
# Idempotency-Key: test-roll-001

# { 
#   "playerId": "cmu49r3g5000210mnzcurjkyh",
#   "dice": [6, 1, 4, 1, 1]
# }

# POST http://localhost:3000/games/cmu45txyw000022qjlgt4d6ny/score
# Content-Type: application/json
# Idempotency-Key: test-score-001

# {
#   "playerId": "cmu49r3g5000210mnzcurjkyh",
#   "category": "four"
# }

# POST http://localhost:3000/games
# Content-Type: application/json
# Idempotency-Key: create-game-test-002

# {
#   "hostName": "piotr"
# }

# POST http://localhost:3000/games HTTP/1.1
# Content-Type: application/json
# Idempotency-Key: auth-test-003

# {
#   "hostName": "Piotr"
# }

# POST http://localhost:3000/games/cmu5v91zh000810qllz26magn/start HTTP/1.1
# Idempotency-Key: start-no-cookie-003

# POST http://localhost:3000/games HTTP/1.1
# Content-Type: application/json
# Idempotency-Key: auth-test-004

# {
#   "hostName": "Piotr"
# }

POST http://localhost:3000/games/cmu5vxvzg000410lbn01yye5y/start HTTP/1.1
Idempotency-Key: start-fake-cookie-0012
Cookie: host_secret=FAKE123

# POST http://localhost:3000/games HTTP/1.1
# Content-Type: application/json
# Idempotency-Key: auth-test-012

# {
#   "hostName": "Piotr"
# }